spring.application.name=autosapi

spring.datasource.url=jdbc:postgresql://dpg-d7v8kdmgvqtc73ce53d0-a.oregon-postgres.render.com/autos_x924

spring.datasource.username=autos_user

spring.datasource.password=gtVyIGniyDjXRItVgXkKKTksmpc9B8Uf

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}