spring.application.name=autosapi

# =========================
# BASE DE DATOS RENDER
# =========================

spring.datasource.url=${SPRING_DATASOURCE_URL}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================

# IMPORTANTE:
# Hibernate NO debe crear tablas
# porque schema.sql ya lo hace

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false

# =========================
# EJECUTAR schema.sql y data.sql
# =========================

spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true

# =========================
# PUERTO RENDER
# =========================

server.port=${PORT:8080}

# =========================
# ERRORES
# =========================

server.error.include-message=always

server.error.include-binding-errors=always

server.error.include-stacktrace=always