spring.application.name=autosapi

# BASE DE DATOS
spring.datasource.url=jdbc:postgresql://dpg-d7v8kdmgvqtc73ce53d0-a.oregon-postgres.render.com/autos_x924

spring.datasource.username=autos_user

spring.datasource.password=gtVyIGniyDjXRItVgXkKKTksmpc9B8Uf

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false

# PUERTO
server.port=${PORT:8080}

# MOSTRAR ERRORES
server.error.include-message=always

server.error.include-binding-errors=always

server.error.include-stacktrace=always

# LOGS
logging.level.org.springframework.web=DEBUG

logging.level.org.hibernate.SQL=DEBUG

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE